# Generated by Django 3.2.8 on 2021-11-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='C:/Users/jakub/Desktop/ecommerce/backend/static/images/sample.jpg', null=True, upload_to=''),
        ),
    ]
